import Navbar from "@/components/Navbar";
import ProgressBarProvider from "@/components/ProgressBarProvider";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "flex flex-col h-screen overflow-hidden antialiased"
        )}
      >
        <ProgressBarProvider />

        <Navbar />

        <main className="flex flex-col flex-1 p-4">{children}</main>

        <Toaster />
      </body>
    </html>
  );
}
